apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: a1.1:latest # Change this to the image you want to use.
          # When using latest tag, default pull policy is Always, thus Kubernetes will try to pull the image even if a local copy is already present.
          # To use the local image, specify imagePullPolicy
          imagePullPolicy: IfNotPresent # or Never
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
